version: '3'

networks:
   work:

services:
  mysql:
    image: mysql:8.0.29
    container_name: "work_mysql"
    restart: unless-stopped
    tty: true
    ports:
    - 4306:3306
    volumes:
    - work-volume:/var/lib/mysql
    -  ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "cermartinezz"
    networks:
      - work
volumes:
  work-volume:
